const INIT_SENSORS = 'INIT_SENSORS';
const SET_PLOT = 'SET_PLOT';
const SET_ACTIVE_SENSOR = 'SET_ACTIVE_SENSOR';
const FETCH_SENSORS_SUCCEEDED = 'FETCH_SENSORS_SUCCEEDED';
const FETCH_SENSORS_PLOT_DATA = 'FETCH_SENSORS_PLOT_DATA';
const FETCH_SENSOR_DATA = 'FETCH_SENSOR_DATA';
const FILL_SENSOR_DATA = 'FILL_SENSOR_DATA';
const SET_PLOT_DATA = 'SET_PLOT_DATA';
const START_FETCH_PLOT_DATA = 'START_FETCH_PLOT_DATA';

export {
    START_FETCH_PLOT_DATA,
    FETCH_SENSOR_DATA,
    SET_PLOT_DATA,
    FILL_SENSOR_DATA,
    FETCH_SENSORS_PLOT_DATA,
    FETCH_SENSORS_SUCCEEDED,
    INIT_SENSORS,
    SET_PLOT,
    SET_ACTIVE_SENSOR
};