const INIT_SENSORS = 'INIT_SENSORS';
const SET_PLOT = 'SET_PLOT';
const SET_ACTIVE_SENSOR = 'SET_ACTIVE_SENSOR';
const FETCH_SENSORS_SUCCEEDED = 'FETCH_SENSORS_SUCCEEDED';

export {
    FETCH_SENSORS_SUCCEEDED,
    INIT_SENSORS,
    SET_PLOT,
    SET_ACTIVE_SENSOR
};